import mysql.connector
import os
import io
import sys

# Force UTF-8 output on Windows
if os.name == 'nt':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

DB_CONFIG = {
    'host': 'localhost',
    'user': 'root',
    'password': '',
    'database': 'smart_recipe_db',
    'charset': 'utf8mb4'
}

INDIAN_RECIPES = [
    {
        "name": "Butter Chicken",
        "description": "A classic North Indian dish with tender chicken pieces simmered in a rich, creamy tomato-butter gravy spiced with aromatic garam masala.",
        "instructions": "1. Cut 500g chicken into 2-inch pieces. Make shallow cuts on each piece for better marination. In a bowl, mix chicken with 1 cup yogurt, 1 tbsp ginger-garlic paste, 1 tsp Kashmiri red chili powder, 1/2 tsp turmeric, and salt. Marinate for at least 2 hours (overnight for best results).\n2. Preheat your oven to 220°C (425°F) or heat a grill pan. Thread chicken onto skewers or place on a baking tray lined with foil. Cook for 15-18 minutes until chicken is charred on the edges and cooked through. Baste with melted butter halfway through cooking.\n3. While chicken cooks, prepare the gravy. Blanch 4 large tomatoes in boiling water for 2 minutes, peel them, and blend into a smooth puree. Set aside.\n4. In a heavy-bottomed pan or kadhai, melt 50g butter over medium heat. Add 1 bay leaf, 2 green cardamom pods, and 4-5 whole cloves. Sauté for 30 seconds until fragrant.\n5. Add 1 finely chopped large onion and cook for 8-10 minutes until deep golden brown, stirring occasionally. Add 1 tbsp ginger-garlic paste and sauté for 2 more minutes until raw smell disappears.\n6. Pour in the tomato puree and cook on medium heat for 12-15 minutes, stirring frequently, until the oil starts separating from the sides. Add 1 tsp garam masala, 1 tsp kasuri methi (dried fenugreek leaves), 1/2 tsp sugar, and salt to taste.\n7. Reduce heat to low and stir in 100ml heavy cream. Mix well to create a smooth, velvety sauce. If the gravy is too thick, add 2-3 tablespoons of warm water.\n8. Add the grilled chicken pieces to the gravy along with any juices. Simmer on low heat for 8-10 minutes, stirring gently, allowing the chicken to absorb the flavors of the sauce.\n9. Finish with a tablespoon of fresh butter and a drizzle of cream on top. Garnish with fresh coriander leaves and a sprinkle of kasuri methi. Serve hot with butter naan, garlic naan, or steamed basmati rice.",
        "prep_time": 45,
        "servings": 4,
        "ingredients": [("chicken", "500g"), ("tomato", "4 large"), ("butter", "50g"), ("heavy cream", "100ml"), ("garlic", "1 tbsp"), ("ginger", "1 tbsp"), ("garam masala", "1 tsp"), ("onion", "1 large")]
    },
    {
        "name": "Palak Paneer",
        "description": "A beloved vegetarian North Indian dish featuring soft paneer cubes nestled in a thick, vibrantly green purée of fresh spinach and aromatic spices.",
        "instructions": "1. Wash 500g fresh spinach leaves thoroughly under running water 3-4 times to remove all dirt and sand. Remove any thick, tough stems. Blanch the spinach in boiling water with a pinch of salt and 1/2 tsp sugar for exactly 2 minutes — the sugar helps retain the bright green color.\n2. Immediately transfer the blanched spinach to a bowl of ice-cold water (this stops the cooking process and locks in the vibrant green color). After 2 minutes, drain well and blend into a smooth puree. Set aside.\n3. Cut 250g paneer into 1-inch cubes. Heat 1 tbsp oil in a non-stick pan over medium heat. Lightly fry the paneer cubes for 2-3 minutes until golden on the edges. Don't overcook — they should still be soft inside. Remove and soak in warm water to keep them soft.\n4. In the same pan, heat 2 tbsp ghee or butter over medium heat. Add 1 tsp cumin seeds and let them splutter for 10 seconds. Add 1 medium finely chopped onion and sauté for 6-7 minutes until translucent and lightly golden.\n5. Add 4 cloves of minced garlic and 1 inch of grated ginger. Cook for 1-2 minutes until fragrant. Add 2 medium chopped tomatoes and cook for 5-6 minutes until they break down and become soft and mushy.\n6. Add 1/2 tsp turmeric, 1 tsp coriander powder, 1/2 tsp cumin powder, 1/4 tsp red chili powder, and salt to taste. Cook for 2 minutes, stirring well to combine the spices with the onion-tomato base.\n7. Pour in the spinach puree and mix thoroughly. Cook on medium-low heat for 5-7 minutes, stirring occasionally. The puree should thicken and become glossy. Add 1/4 cup water if it becomes too thick.\n8. Add 1 tsp garam masala and stir well. Gently slide in the paneer cubes from the warm water (drain first). Fold them in carefully without breaking. Simmer for 3-4 minutes on low heat.\n9. Finish by stirring in 2 tbsp fresh cream and a small knob of butter. Check seasoning and adjust salt. Garnish with a swirl of cream and serve hot with naan, roti, or jeera rice.",
        "prep_time": 30,
        "servings": 3,
        "ingredients": [("paneer", "250g"), ("spinach", "500g"), ("onion", "1 medium"), ("tomato", "2 medium"), ("garlic", "4 cloves"), ("ginger", "1 inch"), ("heavy cream", "2 tbsp"), ("garam masala", "1 tsp")]
    },
    {
        "name": "Chicken Biryani",
        "description": "A fragrant and flavorful layered rice dish featuring marinated chicken, aromatic basmati rice, caramelized onions, saffron, and a blend of whole spices — slow-cooked in the traditional dum style.",
        "instructions": "1. Wash 500g basmati rice gently in cold water 3-4 times until the water runs clear. Soak the rice in plenty of water for exactly 30 minutes — this ensures even, elongated grains during cooking. Drain and set aside.\n2. In a large bowl, combine 1kg chicken pieces (bone-in for best flavor) with 200g yogurt, 1 tbsp ginger-garlic paste, 2 tbsp biryani masala, 1 tsp red chili powder, juice of 1 lemon, salt to taste, and 2 tbsp vegetable oil. Mix well and marinate for at least 1 hour (4 hours refrigerated is ideal).\n3. Soak a pinch of saffron strands (about 20-25 strands) in 3 tablespoons of warm milk. Set aside for 15 minutes — this will create beautiful golden streaks in the biryani.\n4. Bring a large pot of water (at least 8 cups) to a vigorous boil. Add 1 bay leaf, 4 green cardamom pods, 4 cloves, 1-inch cinnamon stick, 1 tsp salt, and 1 tbsp oil. Add the drained rice and parboil for exactly 5-6 minutes until the rice is 70% cooked (it should still have a slight bite in the center). Drain immediately in a colander.\n5. Thinly slice 4 large onions into half-rings. Deep fry them in batches in hot oil (175°C/350°F) until deep golden brown and crispy — this takes about 8-10 minutes per batch. Drain on paper towels. These fried onions (birista) are crucial for the biryani's flavor. Reserve a handful for garnishing.\n6. In a heavy-bottomed pot (ideally a thick aluminum or cast-iron handi), spread the marinated chicken evenly across the bottom. Sprinkle half the fried onions and half the mint and coriander leaves over the chicken.\n7. Layer the parboiled rice evenly on top. Drizzle the saffron milk in lines across the surface. Dot with 2 tablespoons of ghee, remaining fried onions, mint, and coriander. Add 2-3 drops of kewra water or rose water for aroma.\n8. Seal the pot tightly with aluminum foil and then place a heavy lid on top (dum technique). Cook on high heat for 3-4 minutes to build steam, then reduce to the lowest heat and cook for 25 minutes. Do not open the lid during this time.\n9. Turn off the heat and let the biryani rest undisturbed for 5 minutes. Open the lid, gently fluff the rice with a fork from the edges, mixing the layers slightly. Serve hot with raita, mirchi ka salan, and a squeeze of lemon.",
        "prep_time": 60,
        "servings": 6,
        "ingredients": [("chicken", "1kg"), ("basmati rice", "500g"), ("onion", "4 large"), ("yogurt", "200g"), ("ginger", "1 tbsp"), ("garlic", "1 tbsp"), ("mint leaves", "1 bunch"), ("coriander leaves", "1 bunch"), ("biryani masala", "2 tbsp")]
    },
    {
        "name": "Chana Masala",
        "description": "A hearty, protein-rich Indian curry made by simmering chickpeas in a deeply spiced onion-tomato masala gravy with a distinctive tangy flavor from dried mango powder.",
        "instructions": "1. If using dried chickpeas, soak 2 cups in plenty of water overnight (8-10 hours). The next day, drain and pressure cook with 4 cups water, 1/2 tsp salt, and a small piece of tea bag or 2 used tea leaves (this gives the deep brown color traditional to Punjabi chole). Cook for 5-6 whistles until chickpeas are tender but not mushy. If using canned, drain and rinse.\n2. Dry roast 1 tbsp coriander seeds, 1 tsp cumin seeds, 2-3 dried red chilies, 4-5 black peppercorns, 2 cloves, 1 small piece of cinnamon, and 2 green cardamom pods in a pan over low heat for 2-3 minutes until fragrant. Let cool, then grind into a fine powder. This is your fresh chana masala.\n3. Heat 3 tbsp mustard oil or vegetable oil in a heavy kadhai or pan over medium heat. Add 1 tsp cumin seeds and let them splutter for 10 seconds. Add 1 bay leaf and a pinch of asafoetida (hing).\n4. Add 2 medium finely chopped onions. Cook on medium heat for 10-12 minutes, stirring regularly, until they turn deep golden brown. Do not rush this step — well-browned onions are the foundation of the dish's flavor.\n5. Add 1 tbsp ginger-garlic paste and cook for 2 minutes. Add 3 medium tomatoes (pureed) along with 1 tsp turmeric, 1 tsp Kashmiri red chili powder, and the freshly ground chana masala. Cook for 8-10 minutes until oil separates from the masala.\n6. Add the cooked chickpeas along with 1 cup of their cooking liquid. Mix well and bring to a boil. Reduce heat to medium-low and simmer for 15-20 minutes, stirring occasionally, until the gravy thickens and coats the chickpeas.\n7. Using a potato masher or the back of a ladle, lightly mash about 1/4 of the chickpeas against the side of the pan. This thickens the gravy naturally and gives it body.\n8. Add 1/2 tsp amchur (dried mango powder) or a squeeze of lemon juice for tanginess. Adjust salt and add 1/2 tsp garam masala. Stir well.\n9. Garnish with freshly chopped coriander leaves, thin slices of raw onion, a wedge of lemon, and thinly sliced green chilies. Serve hot with bhature, puri, or steamed rice.",
        "prep_time": 40,
        "servings": 4,
        "ingredients": [("chickpeas", "2 cups"), ("onion", "2 medium"), ("tomato", "3 medium"), ("garlic", "1 tbsp"), ("ginger", "1 tbsp"), ("chana masala powder", "1.5 tbsp"), ("coriander leaves", "2 tbsp")]
    },
    {
        "name": "Aloo Gobi",
        "description": "A popular North Indian vegetarian classic featuring potatoes and cauliflower florets gently dry-roasted with turmeric, cumin, and aromatic spices until golden and tender.",
        "instructions": "1. Wash and cut 1 medium cauliflower head into bite-sized florets (about 1.5 inches). Soak in salted warm water for 10 minutes to remove any insects, then drain well. Peel and cut 2 large potatoes into 1-inch cubes. Pat both vegetables dry with a kitchen towel — dry vegetables will roast better and not steam.\n2. Heat 3 tbsp mustard oil or vegetable oil in a large, wide pan or kadhai over medium-high heat. When the oil begins to shimmer (and the pungency of mustard oil reduces), add the potato cubes. Fry for 5-6 minutes, turning occasionally, until they develop a light golden crust on the outside. Remove and set aside.\n3. In the same oil, add the cauliflower florets in a single layer (work in batches if needed). Fry for 4-5 minutes until they get golden spots. Remove and set aside with the potatoes.\n4. Reduce heat to medium. Add 1 tsp cumin seeds to the remaining oil and let them splutter for 10 seconds. Add 1 medium chopped onion and cook for 4-5 minutes until soft. Add 3 cloves of minced garlic and 1 inch of grated ginger. Sauté for 1 minute.\n5. Add 1 medium diced tomato and cook for 3-4 minutes until soft. Add 1/2 tsp turmeric powder, 1 tsp coriander powder, 1/2 tsp cumin powder, 1/2 tsp red chili powder, and salt to taste. Stir well and cook spices for 2 minutes.\n6. Return the par-fried potatoes and cauliflower to the pan. Toss gently to coat all pieces evenly with the spice mixture. Add 2-3 tablespoons of water, cover with a lid, and reduce heat to low.\n7. Cook covered for 12-15 minutes, lifting the lid and stirring gently every 4-5 minutes to prevent sticking. The vegetables should be fork-tender but not mushy. If they start sticking, sprinkle a tablespoon of water.\n8. Once done, remove the lid, increase heat to medium for 2 minutes to evaporate any remaining moisture. This step gives the dish a dry, roasted texture.\n9. Sprinkle 1/2 tsp garam masala and squeeze half a lemon over the dish. Garnish generously with fresh cilantro leaves and a slit green chili. Serve hot with roti, paratha, or dal-rice.",
        "prep_time": 25,
        "servings": 4,
        "ingredients": [("cauliflower", "1 medium head"), ("potato", "2 large"), ("onion", "1 medium"), ("tomato", "1 medium"), ("garlic", "3 cloves"), ("ginger", "1 inch"), ("turmeric", "1/2 tsp"), ("coriander leaves", "2 tbsp")]
    },
    {
        "name": "Dal Makhani",
        "description": "An iconic Punjabi dish of whole black lentils and kidney beans slow-simmered for hours with butter, cream, and spices until rich, creamy, and deeply flavorful.",
        "instructions": "1. Wash 1 cup whole black lentils (urad dal) and 1/4 cup kidney beans (rajma) separately under running water. Soak both together in plenty of water overnight (at least 8 hours). The lentils will nearly double in size.\n2. Drain the soaked lentils and beans. Add them to a pressure cooker with 4 cups water, 1/2 tsp salt, and 1/4 tsp turmeric. Pressure cook on medium-high heat for 20-25 minutes (about 10-12 whistles) until the lentils are completely soft and creamy. The beans should mash easily between your fingers.\n3. Using a wooden spoon or whisk, mash about a third of the cooked lentils against the side of the pot. This creates the signature creamy texture. Do not drain the cooking liquid — it's the base of your gravy.\n4. In a separate heavy-bottomed pan (or the same pot after transferring), heat 3 tbsp butter over medium heat. Add 1 tsp cumin seeds, 2 bay leaves, 4 green cardamom pods (lightly crushed), and 4-5 cloves. Sauté for 30 seconds until aromatic.\n5. Add 1 large finely chopped onion and cook for 8-10 minutes until deep golden brown, stirring regularly. Add 1 tbsp ginger-garlic paste and cook for 2 minutes until the raw aroma disappears.\n6. Add 1 cup tomato puree (about 3-4 medium tomatoes blended), 1 tsp Kashmiri red chili powder, 1 tsp coriander powder, and 1/2 tsp garam masala. Cook for 8-10 minutes on medium heat, stirring occasionally, until oil separates from the masala.\n7. Add the cooked dal-rajma mixture to this masala and mix thoroughly. Add 1 cup warm water if the consistency is too thick. Bring to a gentle boil, then reduce heat to the lowest setting.\n8. Simmer uncovered on very low heat for 45-60 minutes, stirring every 10-12 minutes to prevent sticking. The dal will darken in color and develop a rich, complex flavor. Add 2 tablespoons of butter during this slow-cooking phase.\n9. In the final 5 minutes, stir in 1/4 cup fresh heavy cream, 1 tbsp butter, 1 tsp kasuri methi (crushed dried fenugreek leaves), and a pinch of sugar. The dal should be thick, creamy, and coat the back of a spoon. Garnish with a drizzle of cream and fresh coriander. Serve with butter naan or steamed basmati rice.",
        "prep_time": 120,
        "servings": 5,
        "ingredients": [("black lentils", "1 cup"), ("kidney beans", "1/4 cup"), ("onion", "1 large"), ("tomato puree", "1 cup"), ("butter", "3 tbsp"), ("heavy cream", "1/4 cup"), ("garlic", "1 tbsp"), ("ginger", "1 tbsp")]
    },
    {
        "name": "Rogan Josh",
        "description": "An aromatic, deeply red Kashmiri lamb curry made with yogurt, fennel, and a blend of signature Kashmiri spices — rich in flavor but not excessively hot.",
        "instructions": "1. Cut 500g bone-in lamb (shoulder or leg preferred) into 2-inch pieces. Wash and pat dry. In a bowl, combine the lamb with 1 cup yogurt that has been whisked smooth, 1/2 tsp turmeric, and 1/2 tsp salt. Marinate for at least 30 minutes.\n2. Prepare the spice blend: dry roast 1 tsp fennel seeds, 2 green cardamom pods, 2 cloves, 1-inch cinnamon stick, and 1/2 tsp black peppercorns in a pan for 2 minutes until fragrant. Cool and grind to a fine powder.\n3. Heat 3 tbsp ghee (clarified butter) in a heavy-bottomed pot or Dutch oven over medium-high heat. Add the lamb pieces in a single layer (work in batches) and brown on all sides for 6-8 minutes total. The browning creates deep flavor. Remove and set aside.\n4. In the same pot, reduce heat to medium. Add 2 medium sliced onions and cook for 10-12 minutes until deeply caramelized and golden brown. Add 2 tsp ginger powder and the freshly ground spice blend. Stir for 1 minute.\n5. Add 1 tbsp Kashmiri red chili powder (this gives the signature deep red color without excessive heat). Cook for 30 seconds, then immediately add 2 tbsp water to prevent the chili from burning.\n6. Return the browned lamb to the pot. Add the marinated yogurt, one tablespoon at a time, stirring constantly after each addition. This prevents the yogurt from curdling. Cook for 5-6 minutes until the yogurt is fully incorporated.\n7. Add 1.5 cups warm water. Bring to a boil, then reduce heat to the lowest setting. Cover tightly and cook for 60-75 minutes until the lamb is fork-tender and nearly falling off the bone.\n8. Remove the lid in the last 10 minutes and increase heat to medium. Let the gravy reduce until it's thick and coats the meat generously. The oil will separate and float on top — this is a sign the rogan josh is ready.\n9. Add 1/2 tsp garam masala and stir gently. Garnish with fresh coriander leaves and a drizzle of ghee. Serve hot with steamed basmati rice or Kashmiri naan.",
        "prep_time": 90,
        "servings": 4,
        "ingredients": [("lamb", "500g"), ("yogurt", "1 cup"), ("onion", "2 medium"), ("kashmiri chili powder", "1 tbsp"), ("fennel powder", "1 tsp"), ("ginger powder", "1/2 tsp"), ("ghee", "3 tbsp")]
    },
    {
        "name": "Samosa",
        "description": "Crispy, golden-brown fried pastry triangles stuffed with a savory spiced potato and pea filling — India's most beloved street food snack.",
        "instructions": "1. Prepare the dough: In a large bowl, combine 2 cups all-purpose flour (maida), 1/4 tsp salt, and 1 tsp ajwain (carom seeds). Add 4 tbsp warm vegetable oil or ghee and rub it into the flour using your fingertips until it resembles breadcrumbs. Gradually add 1/3 cup cold water, little by little, kneading to form a firm, smooth dough. It should not be soft like roti dough. Cover with a damp cloth and rest for 30 minutes.\n2. While the dough rests, prepare the filling. Boil 3 large potatoes until just fork-tender (not mushy — about 15-18 minutes). Peel and roughly mash them, keeping some small chunks for texture.\n3. Heat 2 tbsp oil in a pan over medium heat. Add 1 tsp cumin seeds and let them splutter. Add 1 tsp finely chopped green chilies and 1/2 inch grated ginger. Sauté for 30 seconds.\n4. Add 1/2 cup green peas (thawed if frozen) and cook for 2-3 minutes. Add the mashed potatoes along with 1 tsp coriander powder, 1/2 tsp garam masala, 1/2 tsp amchur (dry mango powder), 1/4 tsp red chili powder, and salt to taste. Mix well and cook for 3-4 minutes. Let the filling cool completely.\n5. Divide the dough into 8 equal balls. Roll each ball into an oval shape (about 6-7 inches long). Cut each oval in half through the center to get two semi-circles.\n6. Take one semi-circle and form a cone by overlapping the straight edges, sealing with a paste of flour and water. Fill the cone with 2-3 tablespoons of the potato filling. Seal the open top edge by pressing firmly with a fork or pinching with wet fingers. Repeat with all pieces.\n7. Heat 2 cups vegetable oil in a deep kadhai or pot to 150°C (300°F) — this is important! Samosas must be fried on LOW-MEDIUM heat first. Gently slide 3-4 samosas into the oil. Fry for 10-12 minutes on low heat, turning occasionally, until the pastry is fully cooked and light golden.\n8. Increase the heat to 180°C (350°F) and fry for another 3-4 minutes until the samosas are deep golden brown and extra crispy. The two-stage frying ensures crispy, flaky layers throughout.\n9. Remove with a slotted spoon and drain on paper towels. Serve hot with green mint-coriander chutney, sweet tamarind chutney, and masala chai.",
        "prep_time": 60,
        "servings": 8,
        "ingredients": [("potato", "3 large"), ("green peas", "1/2 cup"), ("flour", "2 cups"), ("vegetable oil", "2 cups for frying"), ("cumin seeds", "1 tsp"), ("coriander powder", "1 tsp"), ("garam masala", "1/2 tsp")]
    },
    {
        "name": "Tandoori Chicken",
        "description": "Iconic smoky, charred chicken marinated in a vibrant yogurt-spice blend and traditionally cooked in a tandoor — recreated at home with oven or grill techniques.",
        "instructions": "1. Take 1 whole chicken (about 1.2 kg), clean it well, and cut into 8 pieces (2 drumsticks, 2 thighs, 2 breast halves, 2 wings). Make 2-3 deep diagonal cuts on each piece, slicing almost to the bone. This allows the marinade to penetrate deeply.\n2. First marination: Rub the chicken pieces generously with 2 tbsp lemon juice, 1 tsp salt, and 1/2 tsp Kashmiri red chili powder. Set aside for 20 minutes. This step tenderizes the meat.\n3. Second marination: In a large bowl, whisk 1 cup thick hung yogurt with 2 tbsp ginger-garlic paste, 2 tbsp tandoori masala, 1 tbsp mustard oil, 1 tsp cumin powder, 1/2 tsp garam masala, 1/2 tsp black pepper, and 1-2 drops of orange/red food color (optional but traditional).\n4. Add the chicken pieces to the yogurt marinade. Mix thoroughly, ensuring marinade gets into every cut and crevice. Cover with plastic wrap and refrigerate for at least 4 hours — overnight gives the best results as the yogurt tenderizes the chicken further.\n5. Remove chicken from the refrigerator 30 minutes before cooking to bring to room temperature. Preheat your oven to the highest setting — 250°C (480°F) with the rack in the upper third. Line a baking sheet with foil and place a wire rack on top.\n6. Arrange chicken pieces on the wire rack with space between each. This allows hot air to circulate and mimic tandoor cooking. Bake for 20-25 minutes. Flip the pieces halfway through.\n7. Switch the oven to broil/grill mode (or move chicken closer to the top element). Broil for 5-7 minutes, watching carefully, until the chicken gets characteristic charred spots — these are key to the authentic tandoori look and smoky flavor.\n8. For extra smokiness (dhungar technique): Place a small steel bowl of hot charcoal inside the pot with chicken. Pour 1 tsp ghee over the charcoal, immediately cover tightly for 2 minutes. The smoke infuses the chicken with authentic tandoor flavor.\n9. Serve on a bed of sliced onion rings with lemon wedges, green mint chutney, and a sprinkle of chaat masala. Pair with naan and a fresh green salad.",
        "prep_time": 120,
        "servings": 4,
        "ingredients": [("chicken", "1 whole, cut into pieces"), ("yogurt", "1 cup"), ("lemon juice", "2 tbsp"), ("ginger-garlic paste", "2 tbsp"), ("tandoori masala", "2 tbsp"), ("mustard oil", "1 tbsp")]
    },
    {
        "name": "Paneer Tikka Masala",
        "description": "Smoky grilled paneer cubes and bell peppers served in a luscious, creamy tomato-onion gravy — a vegetarian showstopper bursting with flavor.",
        "instructions": "1. Cut 250g paneer into 1.5-inch cubes. Cut 1 large bell pepper and 1 medium onion into similar-sized squares for even grilling. These will be threaded onto skewers together.\n2. Prepare the tikka marinade: In a bowl, combine 1/2 cup thick yogurt (hung for 20 minutes), 1 tbsp ginger-garlic paste, 1 tsp Kashmiri red chili powder, 1/2 tsp turmeric, 1 tsp coriander powder, 1/2 tsp garam masala, 1 tbsp oil, and salt. Mix well.\n3. Add paneer cubes, bell pepper pieces, and onion squares to the marinade. Gently toss to coat everything evenly. Marinate for 30-45 minutes at room temperature.\n4. Thread marinated paneer and vegetables alternately onto skewers (or arrange on a baking tray). Grill in a preheated oven at 220°C (425°F) for 12-15 minutes, turning once, until the paneer has slight char marks and the vegetables are slightly blistered. Alternatively, cook on a hot grill pan basted with butter.\n5. While the tikka cooks, prepare the masala gravy. Blend 3 medium tomatoes, 1 medium onion (rough-chopped), and 10-12 cashew nuts with 2 tbsp water into a very smooth puree.\n6. Heat 2 tbsp butter in a pan over medium heat. Add 1 tsp cumin seeds, 1 bay leaf, and 2 green cardamoms. When the cumin splutters, add 1 tbsp ginger-garlic paste and sauté for 1-2 minutes.\n7. Pour in the blended puree and cook for 12-15 minutes on medium heat, stirring frequently, until the oil separates and the gravy turns a deep reddish-orange color. Add 1 tsp Kashmiri red chili powder, 1/2 tsp turmeric, 1 tsp coriander powder, and salt.\n8. Reduce heat to low and stir in 2 tbsp fresh cream. Add 1/2 cup warm water for desired consistency. Simmer for 3-4 minutes. Add 1 tsp kasuri methi (crushed dried fenugreek leaves) and 1/2 tsp sugar to balance the acidity.\n9. Gently add the grilled paneer tikka and vegetables to the gravy. Simmer on low for 3-4 minutes to let the tikka absorb the sauce flavors. Garnish with fresh cream, coriander, and serve hot with garlic naan or jeera rice.",
        "prep_time": 40,
        "servings": 3,
        "ingredients": [("paneer", "250g"), ("bell pepper", "1 large"), ("onion", "2 medium"), ("tomato", "3 medium"), ("yogurt", "1/2 cup"), ("heavy cream", "2 tbsp"), ("ginger-garlic paste", "1 tbsp")]
    },
    {
        "name": "Matar Paneer",
        "description": "A comforting North Indian curry of soft paneer cubes and sweet green peas simmered in a mild, lightly spiced tomato-onion gravy — perfect everyday comfort food.",
        "instructions": "1. Cut 200g paneer into 3/4-inch cubes. Heat 1 tbsp oil in a non-stick pan and lightly fry the paneer cubes until golden on the edges (2-3 minutes). Remove and soak in warm water to keep soft.\n2. Blend 2 medium onions (rough chopped) with 1 tbsp ginger-garlic paste and 2 tbsp water into a smooth paste. Also puree 2 medium tomatoes separately.\n3. Heat 2 tbsp oil or ghee in a heavy pan over medium heat. Add 1 tsp cumin seeds, 1 bay leaf, and 2 green cardamom pods. Let the cumin splutter.\n4. Add the onion paste and cook for 10-12 minutes on medium heat, stirring continuously, until the paste turns golden brown and the raw smell completely disappears. This is the foundation of the gravy.\n5. Add 1/2 tsp turmeric, 1 tsp coriander powder, 1/2 tsp red chili powder, and cook for 1 minute. Pour in the tomato puree and cook for 6-8 minutes until the oil separates from the masala.\n6. Add 1 cup warm water and bring to a simmer. Add 1 cup green peas (fresh or frozen). Cover and cook for 8-10 minutes until peas are tender but still bright green.\n7. Drain the paneer cubes from warm water and gently add them to the gravy. Add 1 tsp garam masala, 1/2 tsp kasuri methi, and salt to taste. Simmer for 5 minutes on low heat.\n8. For a richer gravy, stir in 1-2 tbsp fresh cream. Adjust the consistency by adding a little warm water if too thick.\n9. Garnish with chopped coriander leaves and a drizzle of cream. Serve with roti, naan, or jeera rice for a satisfying vegetarian meal.",
        "prep_time": 30,
        "servings": 4,
        "ingredients": [("paneer", "200g"), ("green peas", "1 cup"), ("onion", "2 medium"), ("tomato", "2 medium"), ("ginger-garlic paste", "1 tbsp"), ("garam masala", "1 tsp"), ("coriander powder", "1 tsp")]
    },
    {
        "name": "Malai Kofta",
        "description": "Luxurious golden fried dumplings made from mashed potato, paneer, and nuts, served floating in a silky, mildly spiced cream-cashew gravy — a dish fit for royalty.",
        "instructions": "1. Boil 2 medium potatoes until fully cooked and soft (about 20 minutes). Peel and mash them thoroughly while still warm — there should be no lumps. Grate 150g paneer finely. In a bowl, combine mashed potato, grated paneer, 2 tbsp cornflour, 1/4 tsp white pepper, and salt.\n2. Finely chop 1 tbsp cashews and 1 tbsp raisins. Divide the potato-paneer mixture into 12-14 equal portions. Take each portion, flatten it, place a few chopped nuts and raisins in the center, and roll into a smooth ball. Ensure there are no cracks.\n3. Heat oil for deep frying to 170°C (340°F). Gently lower 4-5 koftas at a time into the oil. Fry on medium heat for 4-5 minutes, turning occasionally, until they are uniformly golden brown. Remove with a slotted spoon and drain on paper towels.\n4. For the gravy, soak 1/4 cup cashews in warm water for 15 minutes. Blend the soaked cashews with 2 tbsp cream and 2 tbsp water into an ultra-smooth paste.\n5. Heat 2 tbsp butter in a pan. Add 1 tsp cumin seeds, 1 bay leaf, and 2 green cardamoms. When cumin splutters, add 1 large finely chopped onion and cook for 8-10 minutes until golden brown.\n6. Add 1 tbsp ginger-garlic paste, cook 2 minutes. Add 1 cup tomato puree, 1/2 tsp turmeric, 1 tsp coriander powder, 1/2 tsp red chili powder. Cook 8-10 minutes until oil separates.\n7. Add the cashew cream paste and stir well. Cook for 3-4 minutes. Add 1 cup warm water and bring to a gentle simmer. The gravy should be smooth, glossy, and coat the back of a spoon.\n8. Add 1/4 cup fresh cream, 1/2 tsp garam masala, 1 tsp sugar, and 1/2 tsp kasuri methi. Simmer on low for 5 minutes. Adjust salt and consistency.\n9. Place the fried koftas in a serving dish and pour the hot gravy over them just before serving (adding too early makes them soggy). Garnish with cream drizzle, chopped coriander, and serve with naan or jeera rice.",
        "prep_time": 50,
        "servings": 4,
        "ingredients": [("potato", "2 medium"), ("paneer", "150g"), ("cashews", "1/4 cup"), ("onion", "1 large"), ("tomato puree", "1 cup"), ("heavy cream", "1/4 cup"), ("garam masala", "1/2 tsp")]
    },
    {
        "name": "Chicken Korma",
        "description": "A Mughlai-style mild, luxuriously creamy chicken curry enriched with cashew paste, yogurt, and aromatic whole spices — delicate, fragrant, and richly satisfying.",
        "instructions": "1. Cut 500g boneless chicken into 2-inch pieces. Marinate with 1/2 cup yogurt, 1/2 tsp turmeric, 1/2 tsp red chili powder, and salt for 30 minutes.\n2. Soak 1/4 cup cashews in warm water for 15 minutes. Blend into a very smooth paste with 2 tbsp water. This paste gives korma its signature creamy richness.\n3. Thinly slice 2 large onions. Heat 3 tbsp ghee in a heavy pot over medium heat. Fry the onions for 12-15 minutes, stirring occasionally, until deep golden brown and caramelized. Remove half and blend with 2 tbsp water into a smooth paste. Reserve the other half.\n4. In the same ghee, add 3 cardamom pods (lightly crushed), 4 cloves, 1-inch cinnamon stick, and 1 bay leaf. Sauté for 30 seconds until aromatic.\n5. Add 1 tbsp ginger-garlic paste and cook for 2 minutes. Add the marinated chicken and cook on medium-high heat for 5-6 minutes until the chicken is sealed on all sides and lightly browned.\n6. Add the blended onion paste and the cashew paste. Stir well and cook for 5-6 minutes until the pastes coat the chicken evenly and the raw cashew smell disappears.\n7. Add 1/2 cup warm water, cover, and reduce heat to low. Simmer for 20-25 minutes until chicken is fully cooked and tender. Stir every 7-8 minutes.\n8. Stir in 2 tbsp fresh cream, the reserved fried onions, 1/2 tsp garam masala, a pinch of nutmeg, and 1 tsp rose water (optional but authentic). Simmer uncovered for 5 minutes.\n9. Garnish with toasted slivered almonds, fresh coriander, and a drizzle of cream. Serve with saffron rice, roomali roti, or butter naan.",
        "prep_time": 45,
        "servings": 4,
        "ingredients": [("chicken", "500g"), ("onion", "2 large"), ("yogurt", "1/2 cup"), ("cashews", "1/4 cup"), ("ginger-garlic paste", "1 tbsp"), ("heavy cream", "2 tbsp"), ("cardamom", "3 pods")]
    },
    {
        "name": "Vindaloo",
        "description": "A fiery, tangy Goan curry with Portuguese roots — meat slow-cooked in a bold, vinegar-spiked chili paste creating an intensely flavorful and aromatic dish.",
        "instructions": "1. Soak 6-8 dried red Kashmiri chilies in 1/2 cup warm water for 20 minutes until softened. In a blender, combine the soaked chilies (with half their soaking water), 1 whole garlic bulb (peeled cloves), 2 inches of ginger, 3 tbsp vinegar (apple cider or palm vinegar), 1 tsp cumin seeds, 1/2 tsp black peppercorns, 4 cloves, 1-inch cinnamon stick, and 1/2 tsp turmeric. Blend into a very smooth, thick paste.\n2. Cut 500g pork (shoulder or belly) or chicken into 2-inch cubes. Place in a non-reactive bowl and coat thoroughly with the vindaloo paste. Cover and marinate in the refrigerator for at least 4 hours — overnight is traditional and gives the deepest flavor.\n3. Heat 3 tbsp vegetable oil in a heavy-bottomed pot over medium-high heat. Remove the meat from the marinade (reserve the paste) and brown the pieces in batches for 3-4 minutes per batch until well-seared on all sides. Set aside.\n4. In the same pot, add 1 tbsp oil if needed. Add 2 medium onions (thinly sliced) and cook for 10-12 minutes until deeply caramelized and jammy.\n5. Add the reserved vindaloo paste and cook on medium heat for 4-5 minutes, stirring constantly, until the paste darkens and the oil starts to separate. The vinegar will create an intensely aromatic steam.\n6. Return the browned meat to the pot. Add 1 cup warm water, 2 tbsp jaggery or brown sugar (this balances the vinegar's acidity), and salt to taste. Stir well.\n7. Bring to a boil, then reduce to the lowest heat. Cover and slow-cook for 45-60 minutes (pork) or 25-30 minutes (chicken) until the meat is fall-apart tender.\n8. Remove the lid and simmer on medium heat for 10-15 minutes, allowing the gravy to reduce and thicken. It should coat the meat generously with a glossy, thick sauce.\n9. The vindaloo actually tastes better the next day as the flavors meld. Serve hot with steamed rice or crusty bread. Garnish with fresh coriander leaves.",
        "prep_time": 60,
        "servings": 4,
        "ingredients": [("pork or chicken", "500g"), ("dry red chilies", "6-8"), ("garlic", "1 whole bulb"), ("ginger", "2 inches"), ("vinegar", "3 tbsp"), ("onion", "2 medium"), ("cumin seeds", "1 tsp")]
    },
    {
        "name": "Rajma Chawal",
        "description": "The ultimate Punjabi comfort food — red kidney beans in a thick, spiced tomato-onion curry served over perfectly steamed basmati rice.",
        "instructions": "1. Soak 1.5 cups kidney beans (rajma) in plenty of water overnight (at least 8-10 hours). The beans should roughly double in size. Drain and rinse. Pressure cook with 4 cups water and 1/2 tsp salt for 25-30 minutes (about 8-10 whistles) until beans are completely soft and easily mashable between fingers.\n2. While rajma cooks, wash 1 cup basmati rice 3-4 times until water runs clear. Soak for 20 minutes. Bring 2 cups water to a boil with 1 tsp salt, 1 tsp ghee, 1 bay leaf, and 2 green cardamom pods. Add drained rice, cover, reduce to lowest heat, and cook for 15 minutes. Remove from heat and let rest covered for 5 minutes. Fluff with a fork.\n3. Heat 2 tbsp oil and 1 tbsp butter in a heavy pan over medium heat. Add 1 tsp cumin seeds and let them splutter. Add a pinch of asafoetida (hing).\n4. Add 2 medium finely chopped onions and cook for 8-10 minutes until golden brown. Add 1 tbsp ginger-garlic paste and sauté for 2 minutes.\n5. Blend 3 medium tomatoes into a smooth puree. Add to the pan with 1/2 tsp turmeric, 1 tbsp rajma masala or chole masala, 1 tsp coriander powder, and 1/2 tsp red chili powder. Cook for 8-10 minutes until oil separates.\n6. Add the boiled rajma along with 1 cup of their cooking liquid. Mix well and bring to a boil. Reduce heat and simmer for 15-20 minutes, stirring occasionally.\n7. Using the back of a ladle, mash about 1/3 of the beans against the side of the pot. This creates the signature thick, creamy gravy consistency.\n8. Add 1/2 tsp garam masala, 1 tbsp butter, and adjust salt. Simmer for 5 more minutes. The gravy should be thick and coating.\n9. Serve the rajma piping hot over steamed basmati rice with sliced raw onion, a squeeze of lemon, and a side of curd or raita.",
        "prep_time": 45,
        "servings": 4,
        "ingredients": [("kidney beans", "1.5 cups"), ("basmati rice", "1 cup"), ("onion", "2 medium"), ("tomato", "3 medium"), ("ginger-garlic paste", "1 tbsp"), ("rajma masala", "1 tbsp"), ("butter", "1 tbsp")]
    },
    {
        "name": "Masala Dosa",
        "description": "Crispy, golden-brown South Indian crepe made from fermented rice-lentil batter, filled with a spiced potato filling and served with sambar and coconut chutney.",
        "instructions": "1. For the batter (prepare 1 day ahead): Soak 2 cups raw rice and 1/2 cup urad dal separately in water for 5-6 hours. Drain and grind each separately — the dal first with minimal water to a fluffy paste, then the rice with just enough water. Combine, add salt and 1/2 tsp fenugreek seeds (ground). Ferment in a warm place for 8-12 hours until the batter doubles in size and smells slightly sour.\n2. For the potato filling: Boil 3 medium potatoes until tender (about 18-20 minutes). Peel and mash roughly — keep some chunks for texture.\n3. Heat 2 tbsp vegetable oil in a pan over medium heat. Add 1/2 tsp mustard seeds and wait for them to pop (10-15 seconds). Add 1 tsp urad dal (dry), 1 sprig curry leaves (about 10-12 leaves), and 2 slit green chilies. Sauté for 30 seconds.\n4. Add 1 large finely chopped onion and cook for 4-5 minutes until translucent. Add 1/4 tsp turmeric, 1/2 tsp salt, and the mashed potatoes. Mix well and cook for 3-4 minutes. Add 2 tbsp chopped coriander and mix. Set aside.\n5. Heat a large flat non-stick tava (griddle) or cast-iron skillet over medium-high heat. When hot, sprinkle a few drops of water — they should sizzle and evaporate immediately. Rub a few drops of oil across the surface.\n6. Pour about 1/3 cup batter in the center of the tava. Using the back of the ladle, spread the batter outward in circular motion to form a thin, even crepe (about 9-10 inches). The dosa should be paper-thin.\n7. Drizzle 1 tsp oil or ghee around the edges and on top of the dosa. Cook on medium heat for 2-3 minutes until the underside is golden brown and crispy. Do NOT flip the dosa.\n8. Place 2-3 tablespoons of the warm potato filling along the center of the dosa. Fold the dosa in half or roll it into a cylinder.\n9. Serve immediately while crispy with sambar, coconut chutney, and tomato chutney. The dosa should be audibly crispy when you break it.",
        "prep_time": 30,
        "servings": 2,
        "ingredients": [("dosa batter", "2 cups"), ("potato", "3 medium"), ("onion", "1 large"), ("mustard seeds", "1/2 tsp"), ("curry leaves", "1 sprig"), ("turmeric", "1/4 tsp"), ("vegetable oil", "2 tbsp")]
    },
    {
        "name": "Pav Bhaji",
        "description": "Mumbai's iconic street food — a vibrant, butter-laden mixed vegetable curry served with toasted, buttery bread rolls and topped with fresh onions, coriander, and lemon.",
        "instructions": "1. Pressure cook 3 medium potatoes, 1 cup cauliflower florets, and 1/2 cup green peas together with 1 cup water and 1/2 tsp salt for 3-4 whistles until very soft. Drain and mash everything together using a potato masher until smooth.\n2. Heat 3 tbsp butter (generous!) in a large flat pan or tava over medium heat. Add 1 tsp cumin seeds and let them splutter.\n3. Add 2 medium finely chopped onions and cook for 6-8 minutes until softened. Add 1 medium finely chopped bell pepper and cook for 3 minutes.\n4. Add 3 medium finely chopped tomatoes and cook for 5-6 minutes until they completely break down and become pulpy.\n5. Add 2 tbsp pav bhaji masala, 1 tsp red chili powder, 1/2 tsp turmeric, and salt to taste. Cook the masala for 2-3 minutes until fragrant and the oil starts to separate.\n6. Add the mashed vegetable mixture to the pan. Mix thoroughly with the masala. Add 1/2 cup water and stir well. Use the masher to further break down any lumps. The bhaji should be thick, smooth, and cohesive.\n7. Cook the bhaji on medium-low heat for 10-12 minutes, stirring and mashing periodically. Add another 2 tbsp butter during this stage. The bhaji should be rich, thick, and glossy with butter.\n8. Toast the pav: Slice 8 bread rolls horizontally. Heat butter generously on a flat tava. Place the pav cut-side down and toast for 2-3 minutes until golden and crispy. Apply more butter while toasting.\n9. Serve the bhaji on a plate, topped with a pat of butter, finely chopped raw onions, fresh coriander leaves, and a generous squeeze of lemon. Arrange the buttered pav alongside. Serve with a side of thinly sliced onion rings and lemon wedges.",
        "prep_time": 40,
        "servings": 4,
        "ingredients": [("potato", "3 medium"), ("cauliflower", "1 cup florets"), ("green peas", "1/2 cup"), ("bell pepper", "1 medium"), ("onion", "2 medium"), ("tomato", "3 medium"), ("pav bhaji masala", "2 tbsp"), ("butter", "50g"), ("bread rolls", "8")]
    },
    {
        "name": "Kadai Paneer",
        "description": "A vibrant, restaurant-style North Indian paneer dish cooked with bell peppers, tomatoes, and freshly ground kadai masala — bold, tangy, and aromatic.",
        "instructions": "1. Prepare fresh kadai masala: Dry roast 1 tbsp coriander seeds, 2-3 dried red Kashmiri chilies, 1 tsp cumin seeds, and 4-5 whole black peppercorns in a pan over low heat for 2-3 minutes until fragrant and slightly darkened. Cool completely and grind coarsely — the masala should have texture, not be a fine powder.\n2. Cut 250g paneer into 1-inch cubes. Cut 1 large bell pepper (capsicum) into 1-inch squares. Slice 2 medium onions into thick petals (not finely chopped — chunky pieces work better).\n3. Heat 2 tbsp oil in a kadhai or wok over medium-high heat. Lightly fry the paneer cubes for 2 minutes until golden on the edges. Remove and set aside.\n4. In the same oil, add 1 tsp cumin seeds. When they splutter, add the onion petals and cook for 3-4 minutes until slightly softened but still crunchy. Add the bell pepper squares and cook for 2 minutes — they should retain their crunch.\n5. Add 1 tbsp ginger-garlic paste and sauté for 1 minute. Add 3 medium tomatoes (roughly chopped) and cook for 6-8 minutes on medium heat until they break down and become pulpy.\n6. Add 1/2 tsp turmeric, the freshly ground kadai masala, and salt to taste. Cook for 2-3 minutes, mixing well.\n7. Add the fried paneer cubes and 2-3 tablespoons of water. Toss everything together and cook on medium heat for 3-4 minutes, allowing the paneer to absorb the flavors.\n8. Add 1/2 tsp garam masala and 1 tbsp butter. Do NOT add cream — kadai paneer is meant to be a dry, bold preparation, not creamy.\n9. Garnish with julienned ginger strips, slit green chilies, and fresh coriander leaves. Serve immediately with hot butter naan or laccha paratha.",
        "prep_time": 30,
        "servings": 3,
        "ingredients": [("paneer", "250g"), ("bell pepper", "1 large"), ("onion", "2 medium"), ("tomato", "3 medium"), ("coriander seeds", "1 tbsp"), ("dry red chilies", "2-3"), ("ginger-garlic paste", "1 tbsp")]
    },
    {
        "name": "Chole Bhature",
        "description": "A beloved Punjabi combination of spiced chickpea curry (chole) and fluffy deep-fried leavened bread (bhature) — a rich, indulgent meal perfect for weekends.",
        "instructions": "1. Soak 2 cups dried chickpeas overnight in plenty of water with 1/4 tsp baking soda. The next day, drain, rinse, and pressure cook with 4 cups water, 2 used tea bags (for dark color), 1/2 tsp salt, and a small piece of cinnamon. Cook for 6-8 whistles until chickpeas are soft but hold their shape.\n2. Prepare the chole masala: Dry roast 1 tbsp coriander seeds, 1 tsp cumin seeds, 2 cloves, 1 black cardamom, and 4-5 whole black peppercorns for 2 minutes. Cool and grind coarsely.\n3. Heat 3 tbsp oil in a heavy pan. Add 1 tsp cumin seeds and a pinch of hing. Add 2 medium finely chopped onions and cook for 10-12 minutes until deep golden.\n4. Add 1 tbsp ginger-garlic paste, cook 2 minutes. Add 2 medium pureed tomatoes, 1 tsp turmeric, 1 tbsp chole masala (fresh ground), 1 tsp red chili powder. Cook 10 minutes until oil separates.\n5. Add the cooked chickpeas with 1 cup cooking liquid. Simmer for 15-20 minutes. Mash a few chickpeas for thickness. Add 1/2 tsp amchur powder and 1 tsp dried pomegranate seed powder (anardana) for tanginess.\n6. For bhature dough: Combine 2 cups all-purpose flour (maida), 2 tbsp yogurt, 1 tbsp oil, 1/4 tsp baking soda, a pinch of sugar, and salt. Knead with warm water into a soft, elastic dough. Cover and rest for 2 hours — the dough should be pillowy soft.\n7. Divide dough into 8-10 balls. Roll each into an oval shape (about 6-7 inches), slightly thick in center and thin at edges.\n8. Heat oil to 180°C (350°F). Gently slide one bhatura into the hot oil. Press lightly with a slotted spoon — it should puff up like a balloon. Fry for 30-40 seconds per side until golden and puffed. Drain on paper towels.\n9. Serve the spicy chole alongside hot, puffed bhature with pickled onion (onions soaked in vinegar, salt, and chili powder), green chutney, and a slice of lemon. Best enjoyed immediately while bhature are still puffy.",
        "prep_time": 60,
        "servings": 4,
        "ingredients": [("chickpeas", "2 cups"), ("all-purpose flour", "2 cups"), ("yogurt", "2 tbsp"), ("onion", "2 medium"), ("tomato", "2 medium"), ("chole masala", "1 tbsp"), ("vegetable oil", "for frying")]
    },
    {
        "name": "Fish Curry",
        "description": "A tangy, spicy South Indian-style fish curry simmered in a coconut milk and tamarind gravy with curry leaves and mustard seeds — coastal comfort food at its finest.",
        "instructions": "1. Clean and cut 500g firm fish fillets (pomfret, kingfish, or cod work best) into 2-inch pieces. Pat dry with paper towels. Marinate with 1/2 tsp turmeric, 1/2 tsp red chili powder, a squeeze of lemon, and salt. Set aside for 15 minutes.\n2. Extract tamarind pulp: Soak a walnut-sized ball of tamarind in 1/2 cup warm water for 15 minutes. Squeeze and strain to get a tangy extract. Alternatively, use 1 tbsp ready-made tamarind paste mixed with 3 tbsp water.\n3. Heat 3 tbsp coconut oil in a heavy pan or clay pot (traditional) over medium heat. Add 1/2 tsp mustard seeds and wait for them to pop. Add 1/2 tsp fenugreek seeds, 1 sprig curry leaves (about 12-15 leaves), and 2-3 dried red chilies. Sauté for 30 seconds.\n4. Add 1 large thinly sliced onion and cook for 5-6 minutes until soft and translucent. Add 2 slit green chilies, 1 inch of sliced ginger, and 4-5 cloves of sliced garlic. Cook for 2 minutes.\n5. Add 2 medium diced tomatoes and cook for 4-5 minutes until soft. Add 1 tsp Kashmiri red chili powder, 1/2 tsp turmeric, 1 tsp coriander powder, and 1/2 tsp black pepper. Stir well and cook for 2 minutes.\n6. Pour in 1 cup coconut milk (first extract/thick milk) and the tamarind extract. Stir gently and bring to a gentle simmer (do not boil vigorously as coconut milk can split). Add salt to taste.\n7. Gently slide the marinated fish pieces into the simmering gravy. Do NOT stir — instead, gently shake the pan to let the gravy cover the fish. Cook on low heat for 8-10 minutes until the fish is cooked through and flakes easily.\n8. Taste the gravy and adjust the balance of sour (tamarind), spicy (chili), and creamy (coconut). The flavors should be well-harmonized. If too thick, add 2-3 tbsp warm water.\n9. Add a final sprig of fresh curry leaves and remove from heat. Let it rest for 10-15 minutes before serving — fish curries taste better after resting. Serve with steamed rice, appam, or tapioca.",
        "prep_time": 35,
        "servings": 4,
        "ingredients": [("fish fillets", "500g"), ("onion", "1 large"), ("tomato", "2 medium"), ("coconut milk", "1 cup"), ("tamarind paste", "1 tbsp"), ("mustard seeds", "1/2 tsp"), ("curry leaves", "1 sprig"), ("turmeric", "1/2 tsp")]
    }
]

def import_indian_recipes():
    print('Connecting to database...')
    conn = mysql.connector.connect(**DB_CONFIG)
    cursor = conn.cursor()

    ingredient_cache = {}
    
    # Pre-load ingredient cache
    cursor.execute('SELECT name, id FROM ingredients')
    for row in cursor.fetchall():
        ingredient_cache[row[0].lower()] = row[1]

    recipes_added = 0

    print(f'Inserting {len(INDIAN_RECIPES)} Indian recipes...')
    for recipe in INDIAN_RECIPES:
        try:
            # Insert recipe
            cursor.execute('''
                INSERT INTO recipes (name, description, instructions, prep_time_minutes, servings, image_url)
                VALUES (%s, %s, %s, %s, %s, %s)
            ''', (
                recipe['name'],
                recipe['description'],
                recipe['instructions'],
                recipe['prep_time'],
                recipe['servings'],
                None # No image for now
            ))
            recipe_id = cursor.lastrowid

            # Process ingredients
            for ing_name, qty in recipe['ingredients']:
                clean_name = ing_name.lower().strip()
                
                # Create ingredient if doesn't exist
                if clean_name not in ingredient_cache:
                    cursor.execute('INSERT IGNORE INTO ingredients (name) VALUES (%s)', (clean_name,))
                    if cursor.lastrowid:
                        ingredient_cache[clean_name] = cursor.lastrowid
                    else:
                        cursor.execute('SELECT id FROM ingredients WHERE name = %s', (clean_name,))
                        ingredient_cache[clean_name] = cursor.fetchone()[0]

                # Link recipe and ingredient
                cursor.execute('''
                    INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity)
                    VALUES (%s, %s, %s)
                ''', (recipe_id, ingredient_cache[clean_name], qty))

            conn.commit()
            recipes_added += 1
            print(f'  Added: {recipe["name"]}')
            
        except Exception as e:
            conn.rollback()
            print(f'  Error adding {recipe["name"]}: {e}')

    cursor.close()
    conn.close()
    print(f'\nSuccessfully added {recipes_added} recipes.')

if __name__ == '__main__':
    import_indian_recipes()
